<?php
require 'connection/conn.php';
echo "--- election ---\n";
$stmt = $conn->query("DESCRIBE election");
print_r($stmt->fetchAll(PDO::FETCH_ASSOC));
echo "\n--- registrars ---\n";
$stmt = $conn->query("DESCRIBE registrars");
print_r($stmt->fetchAll(PDO::FETCH_ASSOC));
echo "\n--- positions ---\n";
$stmt = $conn->query("DESCRIBE positions");
print_r($stmt->fetchAll(PDO::FETCH_ASSOC));
echo "\n--- cont_details ---\n";
$stmt = $conn->query("DESCRIBE cont_details");
print_r($stmt->fetchAll(PDO::FETCH_ASSOC));
echo "\n--- vote_counts ---\n";
$stmt = $conn->query("DESCRIBE vote_counts");
print_r($stmt->fetchAll(PDO::FETCH_ASSOC));
echo "\n--- voterhasdone ---\n";
$stmt = $conn->query("DESCRIBE voterhasdone");
print_r($stmt->fetchAll(PDO::FETCH_ASSOC));
