ALTER TABLE election
ADD COLUMN allow_email_login TINYINT(1) DEFAULT 1,
ADD COLUMN allow_sms_login TINYINT(1) DEFAULT 0,
ADD COLUMN allow_pin_login TINYINT(1) DEFAULT 0;

ALTER TABLE voters
MODIFY COLUMN email VARCHAR(255) NULL,
ADD COLUMN phone VARCHAR(50) NULL,
ADD COLUMN otp_code VARCHAR(10) NULL,
ADD COLUMN otp_expires_at DATETIME NULL;
